### ISSUE TITLE
transactionReceipt always return nil on iOS 9 Beta2

### ISSUE THREAD

**Issue by JayZhao** [mattt/CargoBay#76]
Although iOS 9 is still  in beta but I believe `transactionReceipt` will officially get retired in the final release and `appStoreReceiptURL` should be used for iOS >= 7. Otherwise lots of code that rely on CargoBay will fail in the IAP validation.

**Comment by VivinoMorten** [comment]
Did you experience any iOS 9 (not beta) issues with Cargobay? Just curious.

**Comment by Yincan** [comment]
in iOS9 release,  __transactionReceipt__ is still there
