### ISSUE TITLE
Memory leak in CBCheckReceiptSecurity function

### ISSUE THREAD

**Issue by NSDestr0yer** [mattt/CargoBay#77]
I think there is a memory leak from SecTrustCopyPublicKey in the CBCheckReceiptSecurity function on line 551 of CargoBay.m - the receiptSigningKey var is never CFRelease'd. If the release is added to the _out label the receiptSigningKey will likely need to be declared and set to NULL at the beginning of the function before the require statements.

**Comment by eebean2** [comment]
CargoBay is obsolete as of iOS 9 and 10.11 with transactionReceipt being removed (the whole variable that CargoBay is writing around)

Sorry
