### ISSUE TITLE
Transaction verification always fails due to incorrect value stored in signatureBlob->_receiptVersion.

### ISSUE THREAD

**Issue by arakul163** [mattt/CargoBay#83]
Verification of the transactions for sandbox account is always fails. Debugger says that value stored in "signatureBlob->_receiptVersion" is equal to 3, but expected to be 2 as described here:

> ```
>          1. Extract receipt version, signature and certificate(s).
>          2. Check receipt version == 2.
>          3. Sanity check that signature is 128 bytes.
>          4. Sanity check certification size <= remaining payload data.
> ```

**Comment by tal007** [comment]
Apple has changed their signature, see accepted solution on [StackOverflow](http://stackoverflow.com/questions/36573180/apples-verificationcontroller-m-failed-verifying-sandbox-in-app-purchase-receip)
